version: "3.3"

services:
  lora:
    container_name: lora
    restart: always
    tty: true
    build:
      context: ../
      dockerfile: ./container/Dockerfile
    volumes:
      - postgresql:/var/lib/postgresql/13/main
    ports:
      - "1700:1700/udp"
      - "8080:8080"
volumes:
  postgresql:
